#!/usr/bin/env python3
"""Render SSH trust assets for ANI node bootstrap.

This helper intentionally renders deterministic text instead of opening SSH
sessions itself. The installer can use the output to update OS images, local
workstations, or already-running nodes through its preferred transport.
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import pathlib
import re
import sys


HOSTS_BEGIN = "# ANI managed hosts begin"
HOSTS_END = "# ANI managed hosts end"


@dataclasses.dataclass(frozen=True)
class Node:
    name: str
    tailscale_ip: str
    management_ip: str
    user: str = "kubercloud"

    @property
    def lower_alias(self) -> str:
        return self.name.lower()


def load_nodes(path: pathlib.Path) -> list[Node]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    raw_nodes = payload.get("nodes")
    if not isinstance(raw_nodes, list) or not raw_nodes:
        raise ValueError("nodes JSON must contain a non-empty 'nodes' list")

    nodes: list[Node] = []
    for raw in raw_nodes:
        if not isinstance(raw, dict):
            raise ValueError("each node entry must be an object")
        nodes.append(
            Node(
                name=str(raw["name"]),
                tailscale_ip=str(raw["tailscale_ip"]),
                management_ip=str(raw["management_ip"]),
                user=str(raw.get("user", "kubercloud")),
            )
        )
    return nodes


def parse_path_list(value: str) -> list[pathlib.Path]:
    return [pathlib.Path(item) for item in re.split(r"[,\s]+", value.strip()) if item]


def nodes_with_user(nodes: list[Node], user: str) -> list[Node]:
    normalized = user.strip()
    if not normalized:
        return nodes
    return [
        Node(
            name=node.name,
            tailscale_ip=node.tailscale_ip,
            management_ip=node.management_ip,
            user=normalized,
        )
        for node in nodes
    ]


def _identity_lines(identity_files: list[str]) -> list[str]:
    return [f"  IdentityFile {identity_file}" for identity_file in identity_files]


def render_ssh_config(
    nodes: list[Node],
    *,
    identity_files: list[str] | None = None,
    include_identities_only: bool = False,
    strict_host_key_checking: str = "accept-new",
) -> str:
    identity_files = identity_files or []
    blocks: list[str] = [
        "# ANI managed SSH config begin",
        "# Generated by repo/scripts/ani_ssh_trust_installer.py",
    ]

    for node in nodes:
        blocks.extend(
            [
                "",
                f"Host {node.name} {node.lower_alias}",
                f"  HostName {node.tailscale_ip}",
                f"  User {node.user}",
                *_identity_lines(identity_files),
                f"  StrictHostKeyChecking {strict_host_key_checking}",
            ]
        )
        if include_identities_only:
            blocks.append("  IdentitiesOnly yes")

        for ip in (node.tailscale_ip, node.management_ip):
            blocks.extend(
                [
                    "",
                    f"Host {ip}",
                    f"  HostName {ip}",
                    f"  User {node.user}",
                    *_identity_lines(identity_files),
                    f"  StrictHostKeyChecking {strict_host_key_checking}",
                ]
            )
            if include_identities_only:
                blocks.append("  IdentitiesOnly yes")

    blocks.append("")
    blocks.append("# ANI managed SSH config end")
    return "\n".join(blocks) + "\n"


def render_hosts_block(nodes: list[Node]) -> str:
    lines = [HOSTS_BEGIN]
    for node in nodes:
        lines.append(f"{node.tailscale_ip} {node.name} {node.lower_alias}")
    lines.append(HOSTS_END)
    return "\n".join(lines) + "\n"


def render_authorized_keys(existing: str, public_keys: list[str]) -> str:
    seen: set[str] = set()
    lines: list[str] = []
    for line in [*existing.splitlines(), *public_keys]:
        normalized = line.strip()
        if not normalized or normalized in seen:
            continue
        seen.add(normalized)
        lines.append(normalized)
    return "\n".join(lines) + "\n"


def _read_public_keys(paths: list[pathlib.Path]) -> list[str]:
    keys: list[str] = []
    for path in paths:
        keys.append(path.expanduser().read_text(encoding="utf-8").strip())
    return keys


def _prompt(
    prompt: str,
    *,
    default: str | None = None,
    required: bool = False,
    input_func=input,
    output_func=print,
) -> str:
    suffix = f" [{default}]" if default is not None else ""
    while True:
        value = input_func(f"{prompt}{suffix}: ").strip()
        if value:
            return value
        if default is not None:
            return default
        if not required:
            return ""
        output_func("Value is required.")


def run_interactive(*, input_func=input, output_func=print) -> int:
    nodes_json = pathlib.Path(
        _prompt("Nodes JSON path", required=True, input_func=input_func, output_func=output_func)
    ).expanduser()
    ssh_user = _prompt("SSH user", default="kubercloud", input_func=input_func, output_func=output_func)
    public_key_raw = _prompt(
        "Public key path(s), comma or space separated",
        required=True,
        input_func=input_func,
        output_func=output_func,
    )
    identity_raw = _prompt(
        "Identity file(s) for generated SSH config",
        default="~/.ssh/id_ed25519_ani_cluster",
        input_func=input_func,
        output_func=output_func,
    )
    existing_authorized = _prompt(
        "Existing authorized_keys path (optional)",
        default="",
        input_func=input_func,
        output_func=output_func,
    )
    output_dir = pathlib.Path(
        _prompt("Output directory", default=".", input_func=input_func, output_func=output_func)
    ).expanduser()

    nodes = nodes_with_user(load_nodes(nodes_json), ssh_user)
    public_keys = _read_public_keys(parse_path_list(public_key_raw))
    existing = ""
    if existing_authorized:
        existing = pathlib.Path(existing_authorized).expanduser().read_text(encoding="utf-8")

    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "ani-ssh-config").write_text(
        render_ssh_config(
            nodes,
            identity_files=[str(path) for path in parse_path_list(identity_raw)],
            include_identities_only=True,
        ),
        encoding="utf-8",
    )
    (output_dir / "ani-hosts").write_text(render_hosts_block(nodes), encoding="utf-8")
    (output_dir / "ani-authorized-keys").write_text(
        render_authorized_keys(existing, public_keys),
        encoding="utf-8",
    )

    output_func(f"Wrote {output_dir / 'ani-ssh-config'}")
    output_func(f"Wrote {output_dir / 'ani-hosts'}")
    output_func(f"Wrote {output_dir / 'ani-authorized-keys'}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=__doc__,
        add_help=False,
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""examples:
  ani_ssh_trust_installer.py interactive
  ani_ssh_trust_installer.py render-ssh-config --nodes-json nodes.json --identity-file '~/.ssh/id_ed25519_ani_cluster' --identities-only
  ani_ssh_trust_installer.py render-hosts --nodes-json nodes.json
  ani_ssh_trust_installer.py render-authorized-keys --existing authorized_keys --public-key admin.pub --public-key deploy.pub
""",
    )
    parser.add_argument("-h", "--help", "-H", action="help", help="show this help message and exit")
    subparsers = parser.add_subparsers(dest="command", required=True)

    subparsers.add_parser("interactive", help="prompt for inputs and write rendered assets")

    ssh_config = subparsers.add_parser("render-ssh-config", help="render SSH Host entries for ANI nodes")
    ssh_config.add_argument("--nodes-json", type=pathlib.Path, required=True)
    ssh_config.add_argument("--identity-file", action="append", default=[])
    ssh_config.add_argument("--identities-only", action="store_true")
    ssh_config.add_argument("--strict-host-key-checking", default="accept-new")

    hosts = subparsers.add_parser("render-hosts", help="render an /etc/hosts block for ANI nodes")
    hosts.add_argument("--nodes-json", type=pathlib.Path, required=True)

    authorized = subparsers.add_parser("render-authorized-keys", help="merge public keys into authorized_keys")
    authorized.add_argument("--existing", type=pathlib.Path)
    authorized.add_argument("--public-key", action="append", type=pathlib.Path, required=True)

    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    if args.command == "interactive":
        return run_interactive()

    if args.command == "render-ssh-config":
        nodes = load_nodes(args.nodes_json)
        sys.stdout.write(
            render_ssh_config(
                nodes,
                identity_files=args.identity_file,
                include_identities_only=args.identities_only,
                strict_host_key_checking=args.strict_host_key_checking,
            )
        )
        return 0

    if args.command == "render-hosts":
        sys.stdout.write(render_hosts_block(load_nodes(args.nodes_json)))
        return 0

    if args.command == "render-authorized-keys":
        existing = args.existing.read_text(encoding="utf-8") if args.existing else ""
        sys.stdout.write(render_authorized_keys(existing, _read_public_keys(args.public_key)))
        return 0

    raise AssertionError(f"unhandled command: {args.command}")


if __name__ == "__main__":
    raise SystemExit(main())
