# Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
import json
import secrets
from urllib import error, parse, request

LAYER = "core"
TITLE = "KuberCloud ANI Core API"
VERSION = "1.0.0"
SERVER_URL = "https://{host}/api/v1"
OPERATIONS = [
    "listAPIKeys",
    "createAPIKey",
    "revokeAPIKey",
    "logout",
    "beginOIDCLogin",
    "postAuthRefresh",
    "completeOIDCLogin",
    "getBranding",
    "listStorageBuckets",
    "createStorageBucket",
    "listEncryptionKeys",
    "createEncryptionKey",
    "deleteEncryptionKey",
    "getEncryptionKey",
    "revokeEncryptionKey",
    "rotateEncryptionKey",
    "sealEncryptionObject",
    "createEncryptionUnsealToken",
    "listStorageFilesystems",
    "createStorageFilesystem",
    "deleteStorageFilesystem",
    "getStorageFilesystem",
    "listFilesystemMountTargets",
    "listGPUInventory",
    "getGPUOccupancy",
    "liveness",
    "getInstanceOperation",
    "listInstances",
    "createInstance",
    "getInstance",
    "createInstanceConsoleSession",
    "listInstanceEvents",
    "createInstanceExecSession",
    "applyInstanceLifecycle",
    "listInstanceLogs",
    "getInstanceMetrics",
    "listInstanceOperations",
    "listInstanceSecurityEvents",
    "listK8sClusters",
    "createK8sCluster",
    "deleteK8sCluster",
    "getK8sCluster",
    "getK8sClusterKubeconfig",
    "listK8sClusterNodePools",
    "createK8sClusterNodePool",
    "deleteK8sClusterNodePool",
    "getK8sClusterNodePool",
    "updateK8sClusterNodePool",
    "proxyK8sClusterAPI",
    "upgradeK8sCluster",
    "listK8sClusterWorkloads",
    "reportTokenUsage",
    "getMeteringUsage",
    "listNetworkLoadBalancers",
    "createNetworkLoadBalancer",
    "deleteNetworkLoadBalancer",
    "getNetworkLoadBalancer",
    "listNetworkRoutes",
    "createNetworkRoute",
    "listNetworkSecurityGroups",
    "createNetworkSecurityGroup",
    "deleteNetworkSecurityGroup",
    "getNetworkSecurityGroup",
    "listNetworkSubnets",
    "createNetworkSubnet",
    "deleteNetworkSubnet",
    "getNetworkSubnet",
    "listNetworkVPCs",
    "createNetworkVPC",
    "deleteNetworkVPC",
    "getNetworkVPC",
    "listStorageObjects",
    "createStorageObject",
    "uploadStorageObject",
    "completeStorageObjectUpload",
    "deleteStorageObject",
    "getStorageObject",
    "downloadStorageObject",
    "listObservabilityAlertRules",
    "createObservabilityAlertRule",
    "deleteObservabilityAlertRule",
    "getObservabilityAlertRule",
    "updateObservabilityAlertRule",
    "queryObservability",
    "readiness",
    "getRegistryImageScanResult",
    "listRegistryProjects",
    "createRegistryProject",
    "createRegistryProjectPullSecret",
    "listRegistryRepositories",
    "listRegistryArtifacts",
    "setRegistryRepositoryPermission",
    "getRegistryProjectScanReport",
    "listSandboxTemplates",
    "listSecrets",
    "createSecret",
    "deleteSecret",
    "getSecret",
    "bindSecret",
    "getTasksTaskId",
    "listVectorStores",
    "createVectorStore",
    "deleteVectorStore",
    "getVectorStore",
    "insertVectorStoreDocuments",
    "searchVectorStore",
    "listStorageVolumes",
    "createStorageVolume",
    "deleteStorageVolume",
    "getStorageVolume",
    "listVolumeSnapshots",
    "createVolumeSnapshot"
]
PATHS = [
    "GET /auth/api-keys",
    "POST /auth/api-keys",
    "DELETE /auth/api-keys/{key_id}",
    "POST /auth/logout",
    "POST /auth/oidc/begin",
    "POST /auth/refresh",
    "POST /auth/token",
    "GET /branding",
    "GET /buckets",
    "POST /buckets",
    "GET /encryption/keys",
    "POST /encryption/keys",
    "DELETE /encryption/keys/{key_id}",
    "GET /encryption/keys/{key_id}",
    "POST /encryption/keys/{key_id}/revoke",
    "POST /encryption/keys/{key_id}/rotate",
    "POST /encryption/seal",
    "POST /encryption/unseal-token",
    "GET /filesystems",
    "POST /filesystems",
    "DELETE /filesystems/{filesystem_id}",
    "GET /filesystems/{filesystem_id}",
    "GET /filesystems/{filesystem_id}/mount-targets",
    "GET /gpu-inventory",
    "GET /gpu-inventory/occupancy",
    "GET /healthz",
    "GET /instance-operations/{operation_id}",
    "GET /instances",
    "POST /instances",
    "GET /instances/{instance_id}",
    "POST /instances/{instance_id}/console",
    "GET /instances/{instance_id}/events",
    "POST /instances/{instance_id}/exec",
    "POST /instances/{instance_id}/lifecycle",
    "GET /instances/{instance_id}/logs",
    "GET /instances/{instance_id}/metrics",
    "GET /instances/{instance_id}/operations",
    "GET /instances/{instance_id}/security-events",
    "GET /k8s-clusters",
    "POST /k8s-clusters",
    "DELETE /k8s-clusters/{cluster_id}",
    "GET /k8s-clusters/{cluster_id}",
    "GET /k8s-clusters/{cluster_id}/kubeconfig",
    "GET /k8s-clusters/{cluster_id}/node-pools",
    "POST /k8s-clusters/{cluster_id}/node-pools",
    "DELETE /k8s-clusters/{cluster_id}/node-pools/{node_pool_id}",
    "GET /k8s-clusters/{cluster_id}/node-pools/{node_pool_id}",
    "PATCH /k8s-clusters/{cluster_id}/node-pools/{node_pool_id}",
    "POST /k8s-clusters/{cluster_id}/proxy",
    "POST /k8s-clusters/{cluster_id}/upgrade",
    "GET /k8s-clusters/{cluster_id}/workloads",
    "POST /metering/token-usage",
    "GET /metering/usage",
    "GET /networks/load-balancers",
    "POST /networks/load-balancers",
    "DELETE /networks/load-balancers/{load_balancer_id}",
    "GET /networks/load-balancers/{load_balancer_id}",
    "GET /networks/routes",
    "POST /networks/routes",
    "GET /networks/security-groups",
    "POST /networks/security-groups",
    "DELETE /networks/security-groups/{security_group_id}",
    "GET /networks/security-groups/{security_group_id}",
    "GET /networks/subnets",
    "POST /networks/subnets",
    "DELETE /networks/subnets/{subnet_id}",
    "GET /networks/subnets/{subnet_id}",
    "GET /networks/vpcs",
    "POST /networks/vpcs",
    "DELETE /networks/vpcs/{vpc_id}",
    "GET /networks/vpcs/{vpc_id}",
    "GET /objects",
    "POST /objects",
    "POST /objects/upload",
    "POST /objects/{object_id}/complete",
    "DELETE /objects/{object_id}",
    "GET /objects/{object_id}",
    "GET /objects/{object_id}/download",
    "GET /observability/alert-rules",
    "POST /observability/alert-rules",
    "DELETE /observability/alert-rules/{rule_id}",
    "GET /observability/alert-rules/{rule_id}",
    "PATCH /observability/alert-rules/{rule_id}",
    "GET /observability/query",
    "GET /readyz",
    "GET /registry/images/scan-result",
    "GET /registry/projects",
    "POST /registry/projects",
    "POST /registry/projects/{project}/pull-secret",
    "POST /registry/projects/{project}/pull-secret/kubernetes-apply",
    "GET /registry/projects/{project}/repositories",
    "GET /registry/projects/{project}/repositories/{repository}/artifacts",
    "POST /registry/projects/{project}/repositories/{repository}/permissions",
    "GET /registry/projects/{project}/scan-report",
    "GET /sandbox-templates",
    "GET /secrets",
    "POST /secrets",
    "DELETE /secrets/{secret_id}",
    "GET /secrets/{secret_id}",
    "POST /secrets/{secret_id}/bindings",
    "GET /tasks/{task_id}",
    "GET /vector-stores",
    "POST /vector-stores",
    "DELETE /vector-stores/{vector_store_id}",
    "GET /vector-stores/{vector_store_id}",
    "POST /vector-stores/{vector_store_id}/documents",
    "POST /vector-stores/{vector_store_id}/search",
    "GET /volumes",
    "POST /volumes",
    "DELETE /volumes/{volume_id}",
    "GET /volumes/{volume_id}",
    "GET /volumes/{volume_id}/snapshots",
    "POST /volumes/{volume_id}/snapshots"
]
SCHEMAS = [
    "APIKeyInfo",
    "AsyncTask",
    "BeginOIDCLoginRequest",
    "BeginOIDCLoginResponse",
    "CompleteOIDCLoginRequest",
    "CoreDevProfileInfo",
    "CreateAPIKeyRequest",
    "CreateAPIKeyResponse",
    "CreateInstanceConsoleSessionRequest",
    "CreateInstanceExecSessionRequest",
    "CreateInstanceRequest",
    "CreateInstanceResponse",
    "CreateNetworkLoadBalancerRequest",
    "CreateNetworkRouteRequest",
    "CreateNetworkSecurityGroupRequest",
    "CreateNetworkSubnetRequest",
    "CreateNetworkVPCRequest",
    "CreateObservabilityAlertRuleRequest",
    "CreateRegistryProjectRequest",
    "CreateRegistryPullSecretRequest",
    "CreateStorageBucketRequest",
    "CreateStorageFilesystemRequest",
    "CreateStorageObjectRequest",
    "CreateStorageVolumeRequest",
    "CreateVectorStoreRequest",
    "CreateVolumeSnapshotRequest",
    "CursorPage",
    "EncryptionKey",
    "EncryptionKeyCreateRequest",
    "EncryptionKeyListResponse",
    "EncryptionKeyRevokeRequest",
    "EncryptionKeyRotateRequest",
    "EncryptionKeyRotationResponse",
    "EncryptionSealRequest",
    "EncryptionSealResponse",
    "EncryptionUnsealTokenRequest",
    "EncryptionUnsealTokenResponse",
    "ErrorResponse",
    "FilesystemMountTarget",
    "FilesystemMountTargetListResponse",
    "GPUInventoryListResponse",
    "GPUInventoryRecord",
    "GPUOccupancyStats",
    "HealthCheck",
    "InstanceConsoleSession",
    "InstanceEvent",
    "InstanceEventListResponse",
    "InstanceExecSession",
    "InstanceLifecycleRequest",
    "InstanceLifecycleResponse",
    "InstanceListResponse",
    "InstanceLogEntry",
    "InstanceLogListResponse",
    "InstanceMetrics",
    "InstanceOperation",
    "InstanceRecord",
    "InstanceSecurityEvent",
    "InstanceSecurityEventListResponse",
    "K8sCluster",
    "K8sClusterCreateRequest",
    "K8sClusterKubeconfig",
    "K8sClusterListResponse",
    "K8sClusterNodePool",
    "K8sClusterNodePoolCreateRequest",
    "K8sClusterNodePoolGPU",
    "K8sClusterNodePoolListResponse",
    "K8sClusterNodePoolUpdateRequest",
    "K8sClusterProxyRequest",
    "K8sClusterProxyResponse",
    "K8sClusterUpgradeRequest",
    "K8sClusterWorkload",
    "K8sClusterWorkloadListResponse",
    "ListAPIKeysResponse",
    "LogoutRequest",
    "MeteringUsageRecord",
    "MeteringUsageResponse",
    "NetworkLoadBalancer",
    "NetworkLoadBalancerListResponse",
    "NetworkLoadBalancerListener",
    "NetworkResourceState",
    "NetworkRoute",
    "NetworkRouteListResponse",
    "NetworkSecurityGroup",
    "NetworkSecurityGroupListResponse",
    "NetworkSecurityGroupRule",
    "NetworkSubnet",
    "NetworkSubnetListResponse",
    "NetworkVPC",
    "NetworkVPCListResponse",
    "ObservabilityAlertRule",
    "ObservabilityAlertRuleListResponse",
    "ObservabilityQueryResponse",
    "RefreshAccessTokenRequest",
    "RefreshAccessTokenResponse",
    "RegistryArtifact",
    "RegistryArtifactListResponse",
    "RegistryPermission",
    "RegistryProject",
    "RegistryProjectListResponse",
    "RegistryProjectScanReport",
    "RegistryPullSecret",
    "RegistryRepository",
    "RegistryRepositoryListResponse",
    "RegistryScanResult",
    "ReportTokenUsageRequest",
    "RevokeStatusResponse",
    "SandboxConfig",
    "SandboxInstanceStatus",
    "SandboxNetworkEgressPolicy",
    "SandboxTemplate",
    "SandboxTemplateListResponse",
    "Secret",
    "SecretBinding",
    "SecretBindingRequest",
    "SecretCreateRequest",
    "SecretListResponse",
    "SetRegistryPermissionRequest",
    "StorageBucketListResponse",
    "StorageBucketRecord",
    "StorageFilesystem",
    "StorageFilesystemListResponse",
    "StorageObject",
    "StorageObjectDownloadInfo",
    "StorageObjectListResponse",
    "StorageObjectUploadRequest",
    "StorageObjectUploadResponse",
    "StorageResourceState",
    "StorageVolume",
    "StorageVolumeListResponse",
    "TokenPairResponse",
    "TokenUsageReport",
    "UpdateObservabilityAlertRuleRequest",
    "VectorStore",
    "VectorStoreDocumentInsertRequest",
    "VectorStoreDocumentInsertResponse",
    "VectorStoreListResponse",
    "VectorStoreSearchHit",
    "VectorStoreSearchRequest",
    "VectorStoreSearchResponse",
    "VectorStoreState",
    "VolumeSnapshotListResponse",
    "VolumeSnapshotRecord",
    "WorkloadIdentityBinding"
]
IDEMPOTENCY_OPERATIONS = [
    "createStorageBucket",
    "createEncryptionKey",
    "revokeEncryptionKey",
    "rotateEncryptionKey",
    "sealEncryptionObject",
    "createStorageFilesystem",
    "createInstance",
    "createInstanceExecSession",
    "applyInstanceLifecycle",
    "createK8sCluster",
    "createK8sClusterNodePool",
    "updateK8sClusterNodePool",
    "proxyK8sClusterAPI",
    "upgradeK8sCluster",
    "reportTokenUsage",
    "createNetworkLoadBalancer",
    "createNetworkRoute",
    "createNetworkSecurityGroup",
    "createNetworkSubnet",
    "createNetworkVPC",
    "createStorageObject",
    "uploadStorageObject",
    "completeStorageObjectUpload",
    "createObservabilityAlertRule",
    "updateObservabilityAlertRule",
    "createRegistryProject",
    "createRegistryProjectPullSecret",
    "setRegistryRepositoryPermission",
    "createSecret",
    "createVectorStore",
    "insertVectorStoreDocuments",
    "createStorageVolume",
    "createVolumeSnapshot"
]
CURSOR_PAGINATION_OPERATIONS = [
    "listStorageBuckets",
    "listEncryptionKeys",
    "listStorageFilesystems",
    "listFilesystemMountTargets",
    "listGPUInventory",
    "listInstances",
    "listInstanceLogs",
    "listInstanceOperations",
    "listK8sClusters",
    "listK8sClusterWorkloads",
    "listNetworkLoadBalancers",
    "listNetworkRoutes",
    "listNetworkSecurityGroups",
    "listNetworkSubnets",
    "listNetworkVPCs",
    "listStorageObjects",
    "listObservabilityAlertRules",
    "listRegistryProjects",
    "listRegistryRepositories",
    "listRegistryArtifacts",
    "listSandboxTemplates",
    "listSecrets",
    "listVectorStores",
    "listStorageVolumes",
    "listVolumeSnapshots"
]
ERROR_CODES = [
    "BAD_REQUEST",
    "CONFLICT",
    "FORBIDDEN",
    "INTERNAL_ERROR",
    "NOT_FOUND",
    "NOT_IMPLEMENTED",
    "PRECONDITION_FAILED",
    "RATE_LIMIT_EXCEEDED",
    "UNAUTHORIZED"
]


class APIError(Exception):
    def __init__(self, code: str, message: str, request_id: str = "", details: dict | None = None):
        super().__init__(message)
        self.code = code
        self.message = message
        self.request_id = request_id
        self.details = dict(details or {})

    def to_dict(self) -> dict:
        payload = {"code": self.code, "message": self.message, "request_id": self.request_id}
        if self.details:
            payload["details"] = self.details
        return payload


class Client:
    def __init__(self, base_url: str | None = None, token: str | None = None, timeout: float = 10.0):
        self.base_url = base_url or SERVER_URL
        self.token = token
        self.timeout = timeout

    def has_operation(self, operation_id: str) -> bool:
        return operation_id in OPERATIONS

    def request(
        self,
        method: str,
        path: str,
        body: dict | None = None,
        params: dict | None = None,
        headers: dict | None = None,
    ) -> dict | list | str | None:
        req = request.Request(
            self._url(path, params),
            data=self._encode_body(body),
            method=method.upper(),
            headers=self._headers(headers, body is not None),
        )
        try:
            with request.urlopen(req, timeout=self.timeout) as response:
                return self._decode_response(response.read(), response.headers.get("Content-Type", ""))
        except error.HTTPError as exc:
            payload = self._decode_response(exc.read(), exc.headers.get("Content-Type", ""))
            if isinstance(payload, dict) and "code" in payload and "message" in payload:
                raise APIError(
                    str(payload["code"]),
                    str(payload["message"]),
                    str(payload.get("request_id", "")),
                    payload.get("details") if isinstance(payload.get("details"), dict) else None,
                ) from exc
            raise

    def _url(self, path: str, params: dict | None = None) -> str:
        base = self.base_url.rstrip("/")
        relative = "/" + path.lstrip("/")
        query = parse.urlencode({key: value for key, value in (params or {}).items() if value is not None})
        return f"{base}{relative}{'?' + query if query else ''}"

    def _headers(self, headers: dict | None = None, has_body: bool = False) -> dict:
        merged = {"Accept": "application/json"}
        if has_body:
            merged["Content-Type"] = "application/json"
        if self.token:
            merged["Authorization"] = f"Bearer {self.token}"
        merged.update(headers or {})
        return merged

    def _encode_body(self, body: dict | None) -> bytes | None:
        if body is None:
            return None
        return json.dumps(body).encode("utf-8")

    def _decode_response(self, payload: bytes, content_type: str) -> dict | list | str | None:
        if not payload:
            return None
        text = payload.decode("utf-8")
        if "application/json" in content_type:
            return json.loads(text)
        return text


def new_idempotency_key(prefix: str = "ani") -> str:
    prefix = prefix or "ani"
    return f"{prefix}_{secrets.token_hex(16)}"


def with_idempotency_key(body: dict | None = None, key: str | None = None) -> dict:
    payload = dict(body or {})
    payload["idempotency_key"] = key or new_idempotency_key()
    return payload


def cursor_params(limit: int | None = None, cursor: str | None = None) -> dict:
    params = {}
    if limit is not None and limit > 0:
        params["limit"] = limit
    if cursor:
        params["cursor"] = cursor
    return params


def is_api_error_code(code: str) -> bool:
    return code in ERROR_CODES
