apiVersion: v1
kind: PersistentVolume
metadata:
  name: ani-vcluster-live-hostpath-pv
  labels:
    app.kubernetes.io/part-of: ani-platform
    app.kubernetes.io/managed-by: ani-core
    ani.kubercloud.io/live-gate: m1-k8s-live-a
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /var/local/ani-pv/vcluster-live
    type: DirectoryOrCreate
