// Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
export const layer = "core" as const;
export const title = "KuberCloud ANI Core API" as const;
export const version = "1.0.0" as const;
export const serverURL = "https://{host}/api/v1" as const;
export const operations = [
  "listAPIKeys",
  "createAPIKey",
  "revokeAPIKey",
  "logout",
  "beginOIDCLogin",
  "postAuthRefresh",
  "completeOIDCLogin",
  "getBranding",
  "listStorageBuckets",
  "createStorageBucket",
  "listEncryptionKeys",
  "createEncryptionKey",
  "deleteEncryptionKey",
  "getEncryptionKey",
  "revokeEncryptionKey",
  "rotateEncryptionKey",
  "sealEncryptionObject",
  "createEncryptionUnsealToken",
  "listStorageFilesystems",
  "createStorageFilesystem",
  "deleteStorageFilesystem",
  "getStorageFilesystem",
  "listFilesystemMountTargets",
  "listGPUInventory",
  "getGPUOccupancy",
  "liveness",
  "getInstanceOperation",
  "listInstances",
  "createInstance",
  "getInstance",
  "createInstanceConsoleSession",
  "listInstanceEvents",
  "createInstanceExecSession",
  "applyInstanceLifecycle",
  "listInstanceLogs",
  "getInstanceMetrics",
  "listInstanceOperations",
  "listInstanceSecurityEvents",
  "listK8sClusters",
  "createK8sCluster",
  "deleteK8sCluster",
  "getK8sCluster",
  "getK8sClusterKubeconfig",
  "listK8sClusterNodePools",
  "createK8sClusterNodePool",
  "deleteK8sClusterNodePool",
  "getK8sClusterNodePool",
  "updateK8sClusterNodePool",
  "proxyK8sClusterAPI",
  "upgradeK8sCluster",
  "listK8sClusterWorkloads",
  "reportTokenUsage",
  "getMeteringUsage",
  "listNetworkLoadBalancers",
  "createNetworkLoadBalancer",
  "deleteNetworkLoadBalancer",
  "getNetworkLoadBalancer",
  "listNetworkRoutes",
  "createNetworkRoute",
  "listNetworkSecurityGroups",
  "createNetworkSecurityGroup",
  "deleteNetworkSecurityGroup",
  "getNetworkSecurityGroup",
  "listNetworkSubnets",
  "createNetworkSubnet",
  "deleteNetworkSubnet",
  "getNetworkSubnet",
  "listNetworkVPCs",
  "createNetworkVPC",
  "deleteNetworkVPC",
  "getNetworkVPC",
  "listStorageObjects",
  "createStorageObject",
  "uploadStorageObject",
  "completeStorageObjectUpload",
  "deleteStorageObject",
  "getStorageObject",
  "downloadStorageObject",
  "listObservabilityAlertRules",
  "createObservabilityAlertRule",
  "deleteObservabilityAlertRule",
  "getObservabilityAlertRule",
  "updateObservabilityAlertRule",
  "queryObservability",
  "readiness",
  "getRegistryImageScanResult",
  "listRegistryProjects",
  "createRegistryProject",
  "createRegistryProjectPullSecret",
  "listRegistryRepositories",
  "listRegistryArtifacts",
  "setRegistryRepositoryPermission",
  "getRegistryProjectScanReport",
  "listSandboxTemplates",
  "listSecrets",
  "createSecret",
  "deleteSecret",
  "getSecret",
  "bindSecret",
  "getTasksTaskId",
  "listVectorStores",
  "createVectorStore",
  "deleteVectorStore",
  "getVectorStore",
  "insertVectorStoreDocuments",
  "searchVectorStore",
  "listStorageVolumes",
  "createStorageVolume",
  "deleteStorageVolume",
  "getStorageVolume",
  "listVolumeSnapshots",
  "createVolumeSnapshot"
] as const;
export const paths = [
  "GET /auth/api-keys",
  "POST /auth/api-keys",
  "DELETE /auth/api-keys/{key_id}",
  "POST /auth/logout",
  "POST /auth/oidc/begin",
  "POST /auth/refresh",
  "POST /auth/token",
  "GET /branding",
  "GET /buckets",
  "POST /buckets",
  "GET /encryption/keys",
  "POST /encryption/keys",
  "DELETE /encryption/keys/{key_id}",
  "GET /encryption/keys/{key_id}",
  "POST /encryption/keys/{key_id}/revoke",
  "POST /encryption/keys/{key_id}/rotate",
  "POST /encryption/seal",
  "POST /encryption/unseal-token",
  "GET /filesystems",
  "POST /filesystems",
  "DELETE /filesystems/{filesystem_id}",
  "GET /filesystems/{filesystem_id}",
  "GET /filesystems/{filesystem_id}/mount-targets",
  "GET /gpu-inventory",
  "GET /gpu-inventory/occupancy",
  "GET /healthz",
  "GET /instance-operations/{operation_id}",
  "GET /instances",
  "POST /instances",
  "GET /instances/{instance_id}",
  "POST /instances/{instance_id}/console",
  "GET /instances/{instance_id}/events",
  "POST /instances/{instance_id}/exec",
  "POST /instances/{instance_id}/lifecycle",
  "GET /instances/{instance_id}/logs",
  "GET /instances/{instance_id}/metrics",
  "GET /instances/{instance_id}/operations",
  "GET /instances/{instance_id}/security-events",
  "GET /k8s-clusters",
  "POST /k8s-clusters",
  "DELETE /k8s-clusters/{cluster_id}",
  "GET /k8s-clusters/{cluster_id}",
  "GET /k8s-clusters/{cluster_id}/kubeconfig",
  "GET /k8s-clusters/{cluster_id}/node-pools",
  "POST /k8s-clusters/{cluster_id}/node-pools",
  "DELETE /k8s-clusters/{cluster_id}/node-pools/{node_pool_id}",
  "GET /k8s-clusters/{cluster_id}/node-pools/{node_pool_id}",
  "PATCH /k8s-clusters/{cluster_id}/node-pools/{node_pool_id}",
  "POST /k8s-clusters/{cluster_id}/proxy",
  "POST /k8s-clusters/{cluster_id}/upgrade",
  "GET /k8s-clusters/{cluster_id}/workloads",
  "POST /metering/token-usage",
  "GET /metering/usage",
  "GET /networks/load-balancers",
  "POST /networks/load-balancers",
  "DELETE /networks/load-balancers/{load_balancer_id}",
  "GET /networks/load-balancers/{load_balancer_id}",
  "GET /networks/routes",
  "POST /networks/routes",
  "GET /networks/security-groups",
  "POST /networks/security-groups",
  "DELETE /networks/security-groups/{security_group_id}",
  "GET /networks/security-groups/{security_group_id}",
  "GET /networks/subnets",
  "POST /networks/subnets",
  "DELETE /networks/subnets/{subnet_id}",
  "GET /networks/subnets/{subnet_id}",
  "GET /networks/vpcs",
  "POST /networks/vpcs",
  "DELETE /networks/vpcs/{vpc_id}",
  "GET /networks/vpcs/{vpc_id}",
  "GET /objects",
  "POST /objects",
    "POST /objects/upload",
    "POST /objects/{object_id}/complete",
    "DELETE /objects/{object_id}",
  "GET /objects/{object_id}",
  "GET /objects/{object_id}/download",
  "GET /observability/alert-rules",
  "POST /observability/alert-rules",
  "DELETE /observability/alert-rules/{rule_id}",
  "GET /observability/alert-rules/{rule_id}",
  "PATCH /observability/alert-rules/{rule_id}",
  "GET /observability/query",
  "GET /readyz",
  "GET /registry/images/scan-result",
  "GET /registry/projects",
  "POST /registry/projects",
  "POST /registry/projects/{project}/pull-secret",
  "GET /registry/projects/{project}/repositories",
  "GET /registry/projects/{project}/repositories/{repository}/artifacts",
  "POST /registry/projects/{project}/repositories/{repository}/permissions",
  "GET /registry/projects/{project}/scan-report",
  "GET /sandbox-templates",
  "GET /secrets",
  "POST /secrets",
  "DELETE /secrets/{secret_id}",
  "GET /secrets/{secret_id}",
  "POST /secrets/{secret_id}/bindings",
  "GET /tasks/{task_id}",
  "GET /vector-stores",
  "POST /vector-stores",
  "DELETE /vector-stores/{vector_store_id}",
  "GET /vector-stores/{vector_store_id}",
  "POST /vector-stores/{vector_store_id}/documents",
  "POST /vector-stores/{vector_store_id}/search",
  "GET /volumes",
  "POST /volumes",
  "DELETE /volumes/{volume_id}",
  "GET /volumes/{volume_id}",
  "GET /volumes/{volume_id}/snapshots",
  "POST /volumes/{volume_id}/snapshots"
] as const;
export const schemas = [
  "APIKeyInfo",
  "AsyncTask",
  "BeginOIDCLoginRequest",
  "BeginOIDCLoginResponse",
  "CompleteOIDCLoginRequest",
  "CoreDevProfileInfo",
  "CreateAPIKeyRequest",
  "CreateAPIKeyResponse",
  "CreateInstanceConsoleSessionRequest",
  "CreateInstanceExecSessionRequest",
  "CreateInstanceRequest",
  "CreateInstanceResponse",
  "CreateNetworkLoadBalancerRequest",
  "CreateNetworkRouteRequest",
  "CreateNetworkSecurityGroupRequest",
  "CreateNetworkSubnetRequest",
  "CreateNetworkVPCRequest",
  "CreateObservabilityAlertRuleRequest",
  "CreateRegistryProjectRequest",
  "CreateRegistryPullSecretRequest",
  "CreateStorageBucketRequest",
  "CreateStorageFilesystemRequest",
  "CreateStorageObjectRequest",
  "CreateStorageVolumeRequest",
  "CreateVectorStoreRequest",
  "CreateVolumeSnapshotRequest",
  "CursorPage",
  "EncryptionKey",
  "EncryptionKeyCreateRequest",
  "EncryptionKeyListResponse",
  "EncryptionKeyRevokeRequest",
  "EncryptionKeyRotateRequest",
  "EncryptionKeyRotationResponse",
  "EncryptionSealRequest",
  "EncryptionSealResponse",
  "EncryptionUnsealTokenRequest",
  "EncryptionUnsealTokenResponse",
  "ErrorResponse",
  "FilesystemMountTarget",
  "FilesystemMountTargetListResponse",
  "GPUInventoryListResponse",
  "GPUInventoryRecord",
  "GPUOccupancyStats",
  "HealthCheck",
  "InstanceConsoleSession",
  "InstanceEvent",
  "InstanceEventListResponse",
  "InstanceExecSession",
  "InstanceLifecycleRequest",
  "InstanceLifecycleResponse",
  "InstanceListResponse",
  "InstanceLogEntry",
  "InstanceLogListResponse",
  "InstanceMetrics",
  "InstanceOperation",
  "InstanceRecord",
  "InstanceSecurityEvent",
  "InstanceSecurityEventListResponse",
  "K8sCluster",
  "K8sClusterCreateRequest",
  "K8sClusterKubeconfig",
  "K8sClusterListResponse",
  "K8sClusterNodePool",
  "K8sClusterNodePoolCreateRequest",
  "K8sClusterNodePoolGPU",
  "K8sClusterNodePoolListResponse",
  "K8sClusterNodePoolUpdateRequest",
  "K8sClusterProxyRequest",
  "K8sClusterProxyResponse",
  "K8sClusterUpgradeRequest",
  "K8sClusterWorkload",
  "K8sClusterWorkloadListResponse",
  "ListAPIKeysResponse",
  "LogoutRequest",
  "MeteringUsageRecord",
  "MeteringUsageResponse",
  "NetworkLoadBalancer",
  "NetworkLoadBalancerListResponse",
  "NetworkLoadBalancerListener",
  "NetworkResourceState",
  "NetworkRoute",
  "NetworkRouteListResponse",
  "NetworkSecurityGroup",
  "NetworkSecurityGroupListResponse",
  "NetworkSecurityGroupRule",
  "NetworkSubnet",
  "NetworkSubnetListResponse",
  "NetworkVPC",
  "NetworkVPCListResponse",
  "ObservabilityAlertRule",
  "ObservabilityAlertRuleListResponse",
  "ObservabilityQueryResponse",
  "RefreshAccessTokenRequest",
  "RefreshAccessTokenResponse",
  "RegistryArtifact",
  "RegistryArtifactListResponse",
  "RegistryPermission",
  "RegistryProject",
  "RegistryProjectListResponse",
  "RegistryProjectScanReport",
  "RegistryPullSecret",
  "RegistryRepository",
  "RegistryRepositoryListResponse",
  "RegistryScanResult",
  "ReportTokenUsageRequest",
  "RevokeStatusResponse",
  "SandboxConfig",
  "SandboxInstanceStatus",
  "SandboxNetworkEgressPolicy",
  "SandboxTemplate",
  "SandboxTemplateListResponse",
  "Secret",
  "SecretBinding",
  "SecretBindingRequest",
  "SecretCreateRequest",
  "SecretListResponse",
  "SetRegistryPermissionRequest",
  "StorageBucketListResponse",
  "StorageBucketRecord",
  "StorageFilesystem",
  "StorageFilesystemListResponse",
  "StorageObject",
  "StorageObjectDownloadInfo",
  "StorageObjectListResponse",
  "StorageObjectUploadRequest",
  "StorageObjectUploadResponse",
  "StorageResourceState",
  "StorageVolume",
  "StorageVolumeListResponse",
  "TokenPairResponse",
  "TokenUsageReport",
  "UpdateObservabilityAlertRuleRequest",
  "VectorStore",
  "VectorStoreDocumentInsertRequest",
  "VectorStoreDocumentInsertResponse",
  "VectorStoreListResponse",
  "VectorStoreSearchHit",
  "VectorStoreSearchRequest",
  "VectorStoreSearchResponse",
  "VectorStoreState",
  "VolumeSnapshotListResponse",
  "VolumeSnapshotRecord",
  "WorkloadIdentityBinding"
] as const;
export const idempotencyOperations = [
  "createStorageBucket",
  "createEncryptionKey",
  "revokeEncryptionKey",
  "rotateEncryptionKey",
  "sealEncryptionObject",
  "createStorageFilesystem",
  "createInstance",
  "createInstanceExecSession",
  "applyInstanceLifecycle",
  "createK8sCluster",
  "createK8sClusterNodePool",
  "updateK8sClusterNodePool",
  "proxyK8sClusterAPI",
  "upgradeK8sCluster",
  "reportTokenUsage",
  "createNetworkLoadBalancer",
  "createNetworkRoute",
  "createNetworkSecurityGroup",
  "createNetworkSubnet",
  "createNetworkVPC",
  "createStorageObject",
  "uploadStorageObject",
  "completeStorageObjectUpload",
  "createObservabilityAlertRule",
  "updateObservabilityAlertRule",
  "createRegistryProject",
  "createRegistryProjectPullSecret",
  "setRegistryRepositoryPermission",
  "createSecret",
  "createVectorStore",
  "insertVectorStoreDocuments",
  "createStorageVolume",
  "createVolumeSnapshot"
] as const;
export const cursorPaginationOperations = [
  "listStorageBuckets",
  "listEncryptionKeys",
  "listStorageFilesystems",
  "listFilesystemMountTargets",
  "listGPUInventory",
  "listInstances",
  "listInstanceLogs",
  "listInstanceOperations",
  "listK8sClusters",
  "listK8sClusterWorkloads",
  "listNetworkLoadBalancers",
  "listNetworkRoutes",
  "listNetworkSecurityGroups",
  "listNetworkSubnets",
  "listNetworkVPCs",
  "listStorageObjects",
  "listObservabilityAlertRules",
  "listRegistryProjects",
  "listRegistryRepositories",
  "listRegistryArtifacts",
  "listSandboxTemplates",
  "listSecrets",
  "listVectorStores",
  "listStorageVolumes",
  "listVolumeSnapshots"
] as const;
export const errorCodes = [
  "BAD_REQUEST",
  "CONFLICT",
  "FORBIDDEN",
  "INTERNAL_ERROR",
  "NOT_FOUND",
  "NOT_IMPLEMENTED",
  "PRECONDITION_FAILED",
  "RATE_LIMIT_EXCEEDED",
  "UNAUTHORIZED"
] as const;

export interface ClientOptions {
  baseURL?: string;
  token?: string;
}

export interface RequestOptions {
  body?: Record<string, unknown>;
  params?: Record<string, string | number | boolean | undefined>;
  headers?: Record<string, string>;
}

export interface APIError {
  code: string;
  message: string;
  request_id: string;
  details?: Record<string, unknown>;
}

export class Client {
  readonly baseURL: string;
  readonly token?: string;

  constructor(options: ClientOptions = {}) {
    this.baseURL = options.baseURL || serverURL;
    this.token = options.token;
  }

  hasOperation(operationID: string): boolean {
    return operations.includes(operationID as typeof operations[number]);
  }

  async request<T = unknown>(method: string, path: string, options: RequestOptions = {}): Promise<T> {
    const response = await fetch(this.url(path, options.params), {
      method: method.toUpperCase(),
      headers: this.headers(options.headers, options.body !== undefined),
      body: options.body === undefined ? undefined : JSON.stringify(options.body),
    });
    const payload = await this.decodeResponse(response);
    if (!response.ok) {
      if (payload && typeof payload === "object" && "code" in payload && "message" in payload) {
        const data = payload as Record<string, unknown>;
        throw apiError(String(data.code), String(data.message), String(data.request_id || ""), data.details as Record<string, unknown> | undefined);
      }
      throw new Error(`ANI API request failed: ${response.status}`);
    }
    return payload as T;
  }

  private url(path: string, params?: RequestOptions["params"]): string {
    const base = this.baseURL.replace(/\/$/, "");
    const relative = path.startsWith("/") ? path : `/${path}`;
    const query = new URLSearchParams();
    for (const [key, value] of Object.entries(params || {})) {
      if (value !== undefined) {
        query.set(key, String(value));
      }
    }
    const suffix = query.toString();
    return `${base}${relative}${suffix ? `?${suffix}` : ""}`;
  }

  private headers(headers?: Record<string, string>, hasBody = false): Record<string, string> {
    return {
      Accept: "application/json",
      ...(hasBody ? { "Content-Type": "application/json" } : {}),
      ...(this.token ? { Authorization: `Bearer ${this.token}` } : {}),
      ...(headers || {}),
    };
  }

  private async decodeResponse(response: Response): Promise<unknown> {
    if (response.status === 204) {
      return undefined;
    }
    const text = await response.text();
    if (!text) {
      return undefined;
    }
    const contentType = response.headers.get("content-type") || "";
    return contentType.includes("application/json") ? JSON.parse(text) : text;
  }
}

export function newIdempotencyKey(prefix = "ani"): string {
  const safePrefix = prefix || "ani";
  const cryptoObj = globalThis.crypto;
  if (cryptoObj?.randomUUID) {
    return `${safePrefix}_${cryptoObj.randomUUID()}`;
  }
  const bytes = new Uint8Array(16);
  if (cryptoObj?.getRandomValues) {
    cryptoObj.getRandomValues(bytes);
  } else {
    for (let i = 0; i < bytes.length; i += 1) {
      bytes[i] = Math.floor(Math.random() * 256);
    }
  }
  return `${safePrefix}_${Array.from(bytes, (value) => value.toString(16).padStart(2, "0")).join("")}`;
}

export function withIdempotencyKey<T extends Record<string, unknown>>(body: T, key = newIdempotencyKey()): T & { idempotency_key: string } {
  return { ...body, idempotency_key: key };
}

export function cursorParams(limit?: number, cursor?: string): Record<string, string> {
  const params: Record<string, string> = {};
  if (limit !== undefined && limit > 0) {
    params.limit = String(limit);
  }
  if (cursor) {
    params.cursor = cursor;
  }
  return params;
}

export function isAPIErrorCode(code: string): boolean {
  return errorCodes.includes(code as typeof errorCodes[number]);
}

export function apiError(code: string, message: string, requestID = "", details?: Record<string, unknown>): APIError {
  return { code, message, request_id: requestID, ...(details ? { details } : {}) };
}
